<a href="https://colab.research.google.com/github/R0ckie/Laboratory-7/blob/main/LinAlg_LAb7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

K = np.array([[2,1,7],
              [4,6,5],
              [1,2,3]])
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
R = np.identity(3)
L = np.array([[9,9,9],
               [5,5,5],
               [3,4,5]])
D = np.zeros([3,3])
B = np.ones([3,4])


def Distributive (matrix1, matrix2, matrix3):
  # A(B+C)=AB+AC = equation
  DPa_bc = matrix1.dot(matrix2 + matrix3)
  print("Distributive: \n" , DPa_bc)
  print('--------------------')
  DPab_c = matrix3.dot(matrix2 + matrix1)
  print(DPab_c)
  print('********************')
Distributive(K,A,L)

def Associative(matrix1, matrix2, matrix3):
  #A(BC)=(AB)C = equation
  #A(BC): 
  APa_bc = matrix1.dot(matrix2.dot(matrix3))
  print("Associative : \n",  APa_bc)
  print('--------------------')
  #(AB)C:
  APab_c =(matrix1.dot(matrix2)).dot(matrix3)
  print(APab_c)
  print('********************')  
Associative(K,A,R)

def notCommutative (matrix1,matrix2):
  # AB≠BA
  #AB
  notCom_ab = np.dot(matrix1,matrix2)
  print("Not Commutative: \n" , notCom_ab)
  print('--------------------')
  #BA
  notCom_ba = np.dot(matrix2,matrix1)
  print(notCom_ba)
  print('********************')  
notCommutative(K,A)

def multiIdentity (matrix1, I):
  multiId = np.dot(matrix1, I)
  print("Mutiplicative Identity: \n", multiId)
  print('********************')  
multiIdentity(A,R)

def mutiIdentityZero (matrix1, Zero):
  multiIdZero = np.dot(matrix1, Zero)
  print("Mutiplicative Identity Zero: \n",multiIdZero)
  print('********************')  
mutiIdentityZero(K,D)

def dimensionProperty (matrix1, matrix2):
  d1 = matrix1.shape[0]
  d2 = matrix2.shape[1]
  print("Dimension Property: \n", d1,d2)
dimensionProperty(A,R)




Distributive: 
 [[ 99 116 133]
 [144 164 184]
 [ 58  67  76]]
--------------------
[[171 216 297]
 [ 95 120 165]
 [ 81 103 134]]
********************
Associative : 
 [[55. 65. 75.]
 [63. 78. 93.]
 [30. 36. 42.]]
--------------------
[[55. 65. 75.]
 [63. 78. 93.]
 [30. 36. 42.]]
********************
Not Commutative: 
 [[55 65 75]
 [63 78 93]
 [30 36 42]]
--------------------
[[ 13  19  26]
 [ 34  46  71]
 [ 55  73 116]]
********************
Mutiplicative Identity: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
********************
Mutiplicative Identity Zero: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
********************
Dimension Property: 
 3 3
